"""
Evaluation module: uses a second Claude call to assess the quality of the generated review.
Demonstrates LLM-as-judge evaluation technique for AI output quality assurance.
"""
import anthropic
import json

EVAL_SYSTEM_PROMPT = """You are an expert AI evaluator assessing the quality of code reviews generated by an AI assistant.

Evaluate the provided code review against the original code and respond ONLY with a valid JSON object:
{
  "score": <integer 1-10>,
  "completeness": <integer 1-10, did it catch all major issues?>,
  "accuracy": <integer 1-10, are the identified issues actually real problems?>,
  "actionability": <integer 1-10, are the fix suggestions clear and implementable?>,
  "verdict": "excellent|good|adequate|poor",
  "missed_issues": ["<any significant issue the review failed to catch>"],
  "false_positives": ["<any issue flagged that is not actually a problem>"],
  "summary": "<one sentence assessment>"
}"""


def evaluate_review(
    client: anthropic.Anthropic,
    code: str,
    language: str,
    review: dict,
) -> dict:
    """
    Uses Claude as a judge to evaluate the quality of a generated code review.
    Returns structured evaluation metrics.
    """
    review_text = json.dumps(review, indent=2)
    prompt = f"""Original {language} code:
```
{code[:3000]}
```

Generated code review:
{review_text[:3000]}

Evaluate this review's quality."""

    try:
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            system=EVAL_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = message.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip().rstrip("```").strip()
        return json.loads(raw)
    except Exception:
        return {
            "score": 0,
            "completeness": 0,
            "accuracy": 0,
            "actionability": 0,
            "verdict": "unavailable",
            "missed_issues": [],
            "false_positives": [],
            "summary": "Evaluation unavailable",
        }
